### 所有的便當外帶打8折

In [5]:
prices = [220, 150, 180, 90, 100, 340]
new_prices = list()
for price in prices:
    new_prices.append(price*0.8)
print(new_prices)

[176.0, 120.0, 144.0, 72.0, 80.0, 272.0]


### 另外一種寫法 

In [7]:
prices = [220, 150, 180, 90, 100, 340]
new_prices = list()
new_prices = [price*0.8 for price in prices]
print(new_prices)

[176.0, 120.0, 144.0, 72.0, 80.0, 272.0]


### 所有的便當外帶打8折 （使用numpy）

In [8]:
import numpy as np

prices = np.array([220, 150, 180, 90, 100, 340])
discount = 0.8
print(prices)
print(prices*discount)

[220 150 180  90 100 340]
[176. 120. 144.  72.  80. 272.]


### 只有超過100元的便當外帶才有8折優惠

In [9]:
import numpy as np
prices = np.array([220, 150, 180, 90, 100, 340])
discount = 0.8
print(prices)
print(prices>100)
target = prices > 100
print(prices*target*discount)

[220 150 180  90 100 340]
[ True  True  True False False  True]
[176. 120. 144.   0.   0. 272.]


### 計算加權成績 （一個同學）

In [12]:
import numpy as np
scores = np.array([80, 95, 45])
weights = np.array([0.3, 0.3, 0.4])
results = scores * weights
print("Your final score is ", results.sum())
print("Your final score is ", scores.dot(weights)) # better method, of course

Your final score is  70.5
Your final score is  70.5


### 計算加權成績（一堆同學）

In [14]:
import numpy as np
scores = np.array([[80, 95, 45], 
                  [50, 78, 65], 
                  [80, 99, 100]])
weights = np.array([0.3, 0.3, 0.4])
results = scores * weights
print("Your final score is ", scores.dot(weights))

Your final score is  [70.5 64.4 93.7]


### 隨機數的應用

In [40]:
import numpy as np
A = np.random.randn(500)
print(A.sum())
print(A.mean())
print(A)

15.995658208301416
0.031991316416602834
[ 0.48916522  0.81685098  0.75101707 -0.05183681  1.02084709  0.26624645
  0.95470615 -1.11995664  0.17603602 -0.79548387 -1.07543    -0.52850806
 -0.15175317 -1.01546411  1.1183758   0.86475877 -0.99938011 -0.939984
 -0.2819875   0.40539891 -0.36198374  0.58979932  1.70184636 -0.99431417
 -0.26939308  1.73909994  0.74843263  0.50246497  1.72645247 -0.2089466
  0.59828629 -1.11522751 -1.002673    0.90967987 -0.33431891 -0.04669697
  0.03472145 -0.68802528  0.31126052 -0.3035872   0.16864962 -1.70834949
  0.72894586 -0.73305218  2.06013359 -0.46026584 -1.27995739  0.51023593
  1.17848528 -0.50313069  1.0966095  -1.93926867  0.09235936  1.13073184
 -0.41415833  0.97210594  0.97993638  1.00681455  0.78625099 -0.49247175
 -2.0535488  -1.09175644 -0.12293219  1.68271553  0.31682326 -0.70261781
  0.8040229  -1.33658722  1.00622458 -1.41142419  0.33300862  0.28735633
 -0.12169826 -1.07380994 -0.82833569 -0.03110693  0.42331687  1.30603882
 -0.11132686 -